spring:
  application:
    name: sso-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 
  datasource:
    url: ${DB_URL}/sso
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: https://eureka-server.lucaslabs.com/eureka/ # URL do Eureka Server
    fetch-registry: true
    register-with-eureka: true
server:
  port: 443

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
env:
  domain:
    name: ${ENV_DOMAIN_NAME}